[project]
name = "mit-6-s184"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "celluloid>=0.2.0",
    "matplotlib>=3.10.9",
    "seaborn>=0.13.2",
    "torch==2.11.0",
    "torchvision==0.26.0",
    "tqdm>=4.70.0",
]

[[tool.uv.index]]
name = "pytorch-cu126"
url = "https://download.pytorch.org/whl/cu126"
explicit = true

[tool.uv.sources]
torch = { index = "pytorch-cu126" }
torchvision = { index = "pytorch-cu126" }

[dependency-groups]
dev = [
    "ipykernel>=7.3.0",
]
